version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=8080
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
