FROM jupyter/datascience-notebook

USER root

RUN apt-get update && \
    apt-get clean && rm -rf var/lib/apt/lists/*

## should install python files in another requirements file here

RUN conda install --debug --yes \
    'pytorch' \
    'scikit-learn' && \
    conda clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER $NB_UID