version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=http://ec2-3-82-143-77.compute-1.amazonaws.com/ --port=8080
